ams:
  version: 1.5.2
  envs:
    AMS_EVENTS_ENABLED: true
    AMS_RESOURCES_ENABLED: true
    AMS_NOTIFY_STAFF_MEMBERSHIP_EVENTS: false
    AMS_NOTIFY_STAFF_ORGANISATION_EVENTS: false
    AMS_REQUIRE_FREE_MEMBERSHIP_APPROVAL: true
