ams:
  version: 1.4.0
  envs:
    AMS_EVENTS_ENABLED: False
    AMS_NOTIFY_STAFF_MEMBERSHIP_EVENTS: false
    AMS_NOTIFY_STAFF_ORGANISATION_EVENTS: false
    AMS_REQUIRE_FREE_MEMBERSHIP_APPROVAL: true
