name: dtta-uat-website
alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED
databases:
  - engine: PG
    name: db
    version: "17"
domains:
  - domain: uat.dtta.org.nz
    type: PRIMARY
features:
  - buildpack-stack=ubuntu-22
ingress:
  rules:
    - component:
        name: django
      match:
        path:
          prefix: /
jobs:
  - envs:
      - key: POSTGRES_HOST
        scope: RUN_AND_BUILD_TIME
        value: ${db.HOSTNAME}
      - key: POSTGRES_PORT
        scope: RUN_AND_BUILD_TIME
        value: ${db.PORT}
      - key: POSTGRES_DB
        scope: RUN_AND_BUILD_TIME
        value: ${db.DATABASE}
      - key: POSTGRES_USER
        scope: RUN_AND_BUILD_TIME
        value: ${db.USERNAME}
      - key: POSTGRES_PASSWORD
        scope: RUN_AND_BUILD_TIME
        value: ${db.PASSWORD}
      - key: DJANGO_SECRET_KEY
        scope: RUN_AND_BUILD_TIME
        value: ${DJANGO_SECRET_KEY}
      - key: DJANGO_ADMIN_URL
        scope: RUN_AND_BUILD_TIME
        value: ${DJANGO_ADMIN_URL}
      - key: DJANGO_ALLOWED_HOSTS
        scope: RUN_AND_BUILD_TIME
        value: ${DJANGO_ALLOWED_HOSTS}
      - key: MAILGUN_API_KEY
        scope: RUN_AND_BUILD_TIME
        value: ${MAILGUN_API_KEY}
      - key: MAILGUN_DOMAIN
        scope: RUN_AND_BUILD_TIME
        value: ${MAILGUN_DOMAIN}
      - key: MAILGUN_API_URL
        scope: RUN_AND_BUILD_TIME
        value: ${MAILGUN_API_URL}
      - key: SENTRY_DSN
        scope: RUN_AND_BUILD_TIME
        value: ${SENTRY_DSN}
      - key: DJANGO_SETTINGS_MODULE
        scope: RUN_AND_BUILD_TIME
        value: config.settings.production
      - key: DATABASE_URL
        scope: RUN_AND_BUILD_TIME
        value: ${db.DATABASE_URL}
      - key: AMS_BILLING_SERVICE_CLASS
        scope: RUN_AND_BUILD_TIME
        value: ${AMS_BILLING_SERVICE_CLASS}
      - key: AMS_BILLING_EMAIL_WHITELIST_REGEX
        scope: RUN_AND_BUILD_TIME
        value: ${AMS_BILLING_EMAIL_WHITELIST_REGEX}
      - key: DISCOURSE_REDIRECT_DOMAIN
        scope: RUN_AND_BUILD_TIME
        value: ${DISCOURSE_REDIRECT_DOMAIN}
      - key: DISCOURSE_CONNECT_SECRET
        scope: RUN_AND_BUILD_TIME
        value: ${DISCOURSE_CONNECT_SECRET}
      - key: DJANGO_MEDIA_PUBLIC_BUCKET_NAME
        scope: RUN_AND_BUILD_TIME
        value: ${DJANGO_MEDIA_PUBLIC_BUCKET_NAME}
      - key: DJANGO_MEDIA_PUBLIC_ENDPOINT_URL
        scope: RUN_AND_BUILD_TIME
        value: ${DJANGO_MEDIA_PUBLIC_ENDPOINT_URL}
      - key: DJANGO_MEDIA_PUBLIC_ACCESS_KEY
        scope: RUN_AND_BUILD_TIME
        value: ${DJANGO_MEDIA_PUBLIC_ACCESS_KEY}
      - key: DJANGO_MEDIA_PUBLIC_SECRET_KEY
        scope: RUN_AND_BUILD_TIME
        value: ${DJANGO_MEDIA_PUBLIC_SECRET_KEY}
      - key: DJANGO_MEDIA_PUBLIC_REGION_NAME
        scope: RUN_AND_BUILD_TIME
        value: ${DJANGO_MEDIA_PUBLIC_REGION_NAME}
      - key: DJANGO_MEDIA_PRIVATE_BUCKET_NAME
        scope: RUN_AND_BUILD_TIME
        value: ${DJANGO_MEDIA_PRIVATE_BUCKET_NAME}
      - key: DJANGO_MEDIA_PRIVATE_ENDPOINT_URL
        scope: RUN_AND_BUILD_TIME
        value: ${DJANGO_MEDIA_PRIVATE_ENDPOINT_URL}
      - key: DJANGO_MEDIA_PRIVATE_ACCESS_KEY
        scope: RUN_AND_BUILD_TIME
        value: ${DJANGO_MEDIA_PRIVATE_ACCESS_KEY}
      - key: DJANGO_MEDIA_PRIVATE_SECRET_KEY
        scope: RUN_AND_BUILD_TIME
        value: ${DJANGO_MEDIA_PRIVATE_SECRET_KEY}
      - key: DJANGO_MEDIA_PRIVATE_REGION_NAME
        scope: RUN_AND_BUILD_TIME
        value: ${DJANGO_MEDIA_PRIVATE_REGION_NAME}
      - key: DJANGO_DEFAULT_FROM_EMAIL
        scope: RUN_AND_BUILD_TIME
        value: ${DJANGO_DEFAULT_FROM_EMAIL}
      - key: DJANGO_EMAIL_SUBJECT_PREFIX
        scope: RUN_AND_BUILD_TIME
        value: ${DJANGO_EMAIL_SUBJECT_PREFIX}
    image:
      tag: ${django_tag}
      registry: digital-technologies-teachers-aotearoa
      registry_credentials: ${registry_credentials}
      registry_type: GHCR
      repository: ams-django
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-1gb-fixed
    kind: PRE_DEPLOY
    name: job-deploy
    run_command: python /app/manage.py deploy_steps
region: syd
services:
  - envs:
      - key: POSTGRES_HOST
        scope: RUN_AND_BUILD_TIME
        value: ${db.HOSTNAME}
      - key: POSTGRES_PORT
        scope: RUN_AND_BUILD_TIME
        value: ${db.PORT}
      - key: POSTGRES_DB
        scope: RUN_AND_BUILD_TIME
        value: ${db.DATABASE}
      - key: POSTGRES_USER
        scope: RUN_AND_BUILD_TIME
        value: ${db.USERNAME}
      - key: POSTGRES_PASSWORD
        scope: RUN_AND_BUILD_TIME
        value: ${db.PASSWORD}
      - key: DJANGO_SECRET_KEY
        scope: RUN_AND_BUILD_TIME
        value: ${DJANGO_SECRET_KEY}
      - key: DJANGO_ADMIN_URL
        scope: RUN_AND_BUILD_TIME
        value: ${DJANGO_ADMIN_URL}
      - key: DJANGO_ALLOWED_HOSTS
        scope: RUN_AND_BUILD_TIME
        value: ${DJANGO_ALLOWED_HOSTS}
      - key: MAILGUN_API_KEY
        scope: RUN_AND_BUILD_TIME
        value: ${MAILGUN_API_KEY}
      - key: MAILGUN_DOMAIN
        scope: RUN_AND_BUILD_TIME
        value: ${MAILGUN_DOMAIN}
      - key: MAILGUN_API_URL
        scope: RUN_AND_BUILD_TIME
        value: ${MAILGUN_API_URL}
      - key: SENTRY_DSN
        scope: RUN_AND_BUILD_TIME
        value: ${SENTRY_DSN}
      - key: DJANGO_SETTINGS_MODULE
        scope: RUN_AND_BUILD_TIME
        value: config.settings.production
      - key: DATABASE_URL
        scope: RUN_AND_BUILD_TIME
        value: ${db.DATABASE_URL}
      - key: AMS_BILLING_SERVICE_CLASS
        scope: RUN_AND_BUILD_TIME
        value: ${AMS_BILLING_SERVICE_CLASS}
      - key: AMS_BILLING_EMAIL_WHITELIST_REGEX
        scope: RUN_AND_BUILD_TIME
        value: ${AMS_BILLING_EMAIL_WHITELIST_REGEX}
      - key: DISCOURSE_REDIRECT_DOMAIN
        scope: RUN_AND_BUILD_TIME
        value: ${DISCOURSE_REDIRECT_DOMAIN}
      - key: DISCOURSE_CONNECT_SECRET
        scope: RUN_AND_BUILD_TIME
        value: ${DISCOURSE_CONNECT_SECRET}
      - key: DJANGO_MEDIA_PUBLIC_BUCKET_NAME
        scope: RUN_AND_BUILD_TIME
        value: ${DJANGO_MEDIA_PUBLIC_BUCKET_NAME}
      - key: DJANGO_MEDIA_PUBLIC_ENDPOINT_URL
        scope: RUN_AND_BUILD_TIME
        value: ${DJANGO_MEDIA_PUBLIC_ENDPOINT_URL}
      - key: DJANGO_MEDIA_PUBLIC_ACCESS_KEY
        scope: RUN_AND_BUILD_TIME
        value: ${DJANGO_MEDIA_PUBLIC_ACCESS_KEY}
      - key: DJANGO_MEDIA_PUBLIC_SECRET_KEY
        scope: RUN_AND_BUILD_TIME
        value: ${DJANGO_MEDIA_PUBLIC_SECRET_KEY}
      - key: DJANGO_MEDIA_PUBLIC_REGION_NAME
        scope: RUN_AND_BUILD_TIME
        value: ${DJANGO_MEDIA_PUBLIC_REGION_NAME}
      - key: DJANGO_MEDIA_PRIVATE_BUCKET_NAME
        scope: RUN_AND_BUILD_TIME
        value: ${DJANGO_MEDIA_PRIVATE_BUCKET_NAME}
      - key: DJANGO_MEDIA_PRIVATE_ENDPOINT_URL
        scope: RUN_AND_BUILD_TIME
        value: ${DJANGO_MEDIA_PRIVATE_ENDPOINT_URL}
      - key: DJANGO_MEDIA_PRIVATE_ACCESS_KEY
        scope: RUN_AND_BUILD_TIME
        value: ${DJANGO_MEDIA_PRIVATE_ACCESS_KEY}
      - key: DJANGO_MEDIA_PRIVATE_SECRET_KEY
        scope: RUN_AND_BUILD_TIME
        value: ${DJANGO_MEDIA_PRIVATE_SECRET_KEY}
      - key: DJANGO_MEDIA_PRIVATE_REGION_NAME
        scope: RUN_AND_BUILD_TIME
        value: ${DJANGO_MEDIA_PRIVATE_REGION_NAME}
      - key: DJANGO_DEFAULT_FROM_EMAIL
        scope: RUN_AND_BUILD_TIME
        value: ${DJANGO_DEFAULT_FROM_EMAIL}
      - key: DJANGO_EMAIL_SUBJECT_PREFIX
        scope: RUN_AND_BUILD_TIME
        value: ${DJANGO_EMAIL_SUBJECT_PREFIX}
    http_port: 5000
    image:
      tag: ${django_tag}
      registry: digital-technologies-teachers-aotearoa
      registry_credentials: ${registry_credentials}
      registry_type: GHCR
      repository: ams-django
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-0.5gb
    name: django
    run_command: /start
